[package]
name = "kukareker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kukareker"

[lib]
name = "kukareker"
crate-type = ["rlib", "staticlib"]

[dependencies]
serde = { workspace = true }

test-engine = { workspace = true }

[build-dependencies]
cfg_aliases = "0.2"
